apiVersion: v1
kind: Service
metadata:
  annotations:
    version: 1.34.0
  labels:
    app: trackeranalytics
  name: trackeranalytics
spec:
  ports:
    - name: analytics
      port: {{ .Values.trackerAnalytics.port }}
      targetPort: {{ .Values.trackerAnalytics.port }}
      protocol: TCP
  selector:
    app: trackeranalytics