apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.appName }}-tracker-analytics-config
data:
  REDIS_HOST: {{ .Values.global.redis.host | quote }}
  REDIS_PORT: {{ .Values.global.redis.port | quote }}
  STREAM_KEY: {{ .Values.global.redis.streamKey | quote }}