apiVersion: v1
kind: Service
metadata:
  annotations:
    version: 1.34.0
  labels:
    app: trackerserver-go
  name: trackerserver-go
spec:
  ports:
    - name: http3
      port: {{ .Values.trackerServerGo.tlsPort }}
      targetPort: {{ .Values.trackerServerGo.tlsPort }}
      protocol: UDP
    - name: quic-l4
      port: {{ .Values.trackerServerGo.quicPort }}
      targetPort: {{ .Values.trackerServerGo.quicPort }}
      protocol: UDP
    - name: http1
      port: {{ .Values.trackerServerGo.port }}
      targetPort: {{ .Values.trackerServerGo.port }}
      protocol: TCP
  selector:
    app: trackerserver-go